name: pytest

on: [push, pull_request]

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: 
              uses: actions/setup-python@v4
              with:
                python-version: '3.11' 
            - name: Install Dependencies
              run: |
                poetry install --no-root --no-interaction
            - name: Run Tests
              run: |
                    poetry run pytest